# Generated by Django 4.1.2 on 2022-10-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0002_restraunts_delete_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restraunts',
            name='RestrauntMenu',
            field=models.TextField(),
        ),
    ]
