# Generated by Django 4.1.2 on 2022-10-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0004_remove_restraunts_restrauntmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunts',
            name='RestrauntMenu',
            field=models.TextField(blank=True),
        ),
    ]
