# Generated by Django 4.1.2 on 2022-10-15 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0005_restraunts_restrauntmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restraunts',
            name='RestrauntMenu',
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish1', models.CharField(max_length=500)),
                ('Dish2', models.CharField(max_length=500)),
                ('Drink', models.CharField(max_length=500)),
                ('MenuId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='RestrauntApp.restraunts')),
            ],
        ),
    ]
